apiVersion: v1
kind: Service
metadata:
  name: bonos-service
  labels:
    app: bonos-service
spec:
  # ClusterIP = solo accesible DENTRO del clúster.
  # Otros servicios lo alcanzan vía DNS interno: http://bonos-service:8001
  type: ClusterIP
  selector:
    app: bonos-service
  ports:
    - name: bonos-ext
      protocol: TCP
      port: 3001        # puerto del Service (DNS interno)
      targetPort: 3001  # puerto del contenedor